### ISSUE TITLE
Cant find `GIT_FILTER_CLEAN`in 1.5.0

### ISSUE THREAD

**Issue by finlaymorrison** [iterative/scmrepo#285]
I have been having some issues with the new 1.5.0 version which are fixed when changing to 1.4.1. I get the following error.

```
Traceback (most recent call last):                                    
  File "/mnt/beegfs/home/pearl089/src/page-segmentation/./run-pipeline-stage.py", line 17, in <module>
    cfg = params_show(stages=args.stage)
  File "/mnt/beegfs/home/pearl089/.conda/envs/segmentation/lib/python3.10/site-packages/dvc/api/show.py", line 390, in params_show
    params = _repo.params.show(
  File "/mnt/beegfs/home/pearl089/.conda/envs/segmentation/lib/python3.10/site-packages/dvc/repo/params/__init__.py", line 8, in show
    return show(self.repo, *args, **kwargs)
  File "/mnt/beegfs/home/pearl089/.conda/envs/segmentation/lib/python3.10/site-packages/dvc/repo/__init__.py", line 60, in wrapper
    return f(repo, *args, **kwargs)
  File "/mnt/beegfs/home/pearl089/.conda/envs/segmentation/lib/python3.10/site-packages/dvc/repo/params/show.py", line 205, in show
    _hide_workspace(repo.scm, res)
  File "/mnt/beegfs/home/pearl089/.conda/envs/segmentation/lib/python3.10/site-packages/dvc/repo/metrics/show.py", line 176, in _hide_workspace
    active_branch = scm.active_branch()
  File "/mnt/beegfs/home/pearl089/.conda/envs/segmentation/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 299, in _backend_func
    backend = self.backends[key]
  File "/mnt/beegfs/home/pearl089/.conda/envs/segmentation/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 57, in __getitem__
    initialized = backend(*self.args, **self.kwargs)
  File "/mnt/beegfs/home/pearl089/.conda/envs/segmentation/lib/python3.10/site-packages/scmrepo/git/backend/pygit2/__init__.py", line 156, in __init__
    from .filter import LFSFilter
  File "/mnt/beegfs/home/pearl089/.conda/envs/segmentation/lib/python3.10/site-packages/scmrepo/git/backend/pygit2/filter.py", line 5, in <module>
    from pygit2 import GIT_FILTER_CLEAN, Filter, Passthrough
ImportError: cannot import name 'GIT_FILTER_CLEAN' from 'pygit2' (/mnt/beegfs/home/pearl089/.conda/envs/segmentation/lib/python3.10/site-packages/pygit2/__init__.py)
ERROR: failed to reproduce 'pretrain': failed to run: ./run-pipeline-stage.py --job-type gpu --stage pretrain --script train.py --data data/pretrain-dataset/dataset.y
  ```
  
From a cursory glance at the pygit2 repository, it seems that `GIT_FILTER_CLEAN` was added only recently, 3 weeks ago from what i see. My assumption is that in the conda package for scmrepo the requirement of pygit2 has not been updated to this newly released version.

**Comment by pmrowla** [comment]
A new conda build for scmrepo 1.5.0 has been released with the corrected dependency versions.
