### ISSUE TITLE
flake8-bandit fail

### ISSUE THREAD

**Issue by karajan1001** [iterative/scmrepo#37]
In both CI, and locally I met 
```bash
Traceback (most recent call last):
  File "/Users/gao/anaconda3/envs/dvc/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/flake8/main/application.py", line 351, in _run
    self.run_checks()
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/flake8/main/application.py", line 264, in run_checks
    self.file_checker_manager.run()
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/flake8/checker.py", line 323, in run
    self.run_serial()
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/flake8/checker.py", line 307, in run_serial
    checker.run_checks()
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/flake8/checker.py", line 494, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/flake8_bandit.py", line 85, in run
    for warn in self._check_source():
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/flake8_bandit.py", line 59, in _check_source
    bnv = BanditNodeVisitor(
TypeError: __init__() missing 1 required positional argument: 'metrics'
```
in cmd `flake8`

This error also appears in other repository (`DVC`) after I `pip install flake8-bandit` manually. So guess it is from `flake8-bandit`?

**Comment by karajan1001** [comment]
`bandit` had released 1.7.3 a new version on 2022 28 Feb. rollback to 1.7.2 can solve this.
